#!/usr/bin/env python3
#
# Copyright (c) 2026 Simon Peter
#
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-or-later
#
# Writes CharacterWidthTable.h from Python's Unicode database. Run it again
# with a newer Python to follow a newer Unicode version:
#
#   python3 Tools/generate-character-width-table.py > CharacterWidthTable.h
#
# The rules are those of wcwidth() in glibc and Markus Kuhn's reference
# implementation, which the programs running in the terminal use to
# position the cursor.

import sys
import unicodedata

MAX_CODE_POINT = 0x10FFFF


def is_zero_width(cp):
    if cp == 0x00AD:  # soft hyphen is visible when it ends a line
        return False
    if 0x1160 <= cp <= 0x11FF:  # Hangul medial vowels and final consonants
        return True
    if cp == 0x200B:  # zero width space
        return True
    return unicodedata.category(chr(cp)) in ("Mn", "Me", "Cf")


def is_wide(cp):
    if unicodedata.east_asian_width(chr(cp)) in ("W", "F"):
        return True
    # Unassigned code points in the ideograph planes are wide as well, so
    # characters newer than this table still take two cells.
    return 0x20000 <= cp <= 0x2FFFD or 0x30000 <= cp <= 0x3FFFD


def ranges(predicate):
    result = []
    start = None
    for cp in range(MAX_CODE_POINT + 2):
        inside = cp <= MAX_CODE_POINT and predicate(cp)
        if inside and start is None:
            start = cp
        elif not inside and start is not None:
            result.append((start, cp - 1))
            start = None
    return result


def emit(name, table):
    print("static const CharacterRange %s[] = {" % name)
    for first, last in table:
        print("    {0x%05X, 0x%05X}," % (first, last))
    print("};")
    print()


print("""/*
 * Copyright (c) 2026 Simon Peter
 *
 * SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-or-later
 */

/* Generated by Tools/generate-character-width-table.py from Unicode %s.
   Do not edit. */
""" % unicodedata.unidata_version)
emit("zeroWidthRanges", ranges(is_zero_width))
emit("wideRanges", ranges(is_wide))
