include $(GNUSTEP_MAKEFILES)/common.make
TEST_TOOL_NAME = t_Selection

ADDITIONAL_CPPFLAGS += -I$(GNUSTEP_MAKEFILES)/TestFramework

t_Selection_OBJC_FILES = t_Selection.m

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/test-tool.make
